//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string RealName { get; set; }
        public string PasswordHash { get; set; }
        public string AvatarUrl { get; set; }
        public string Bio { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool IsVerified { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> LastLoginAt { get; set; }
        public string Locale { get; set; }
        public string DevicePreference { get; set; }
        public string EcomStatus { get; set; }
    }
}
